# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ ]



jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
    - uses: actions/checkout@v2
    - name: Artifact Name
      if: runner.os == 'macOS'
      run: |
           JARPATH=$(find . -type f -iname 'test*.txt')
           echo "Found jar path: ${JARPATH}"
           echo "Setting artifactpath to ${JARPATH}"
           echo "::set-env name=artifactpath=${JARPATH}"

           JARNAME=$(basename $JARPATH)
           echo "Found jar path: ${JARPATH}"
           echo "Setting artifactpath to ${JARPATH}"
           echo "::set-env name=artifactpath=${JARPATH}"
           echo "Setting artifactname to ${JARNAME}"
           echo "::set-env name=artifactname::${JARNAME}"
#           (echo "::set-env name=artifactname::$(find . -type f -iname 'test*' -exec basename {} \;)"
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: runner.os == 'macOS'
      with:
        name: ${{env.artifactname}}
        path: ${{env.artifactpath}}
